COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
CXXFLAGS += -DESPRESSIO_THREADS
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_MAJOR=1
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_MINOR=3
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_STRING=\"1.3.0\"
