name=ESPressio-Threads
version=1.4.0
author=Simon J. Stuart
maintainer=Flowduino.com
sentence=Threading library for single- and multi-core ESP32 microcontrollers
paragraph=Thread management for the ESP32 family using ESP-IDF FreeRTOS APIs with either the Arduino or ESP-IDF framework.
category=Data Processing
url=https://github.com/Flowduino/ESPressio-Threads
architectures=esp32
includes=ESPressio_Thread.hpp,ESPressio_PrecisionThread.hpp
depends=Flowduino ESPressio-Timing (>=1.1.0),Flowduino ESPressio-Observable (>=2.0.0)
